# Generated by Django 3.1.2 on 2020-10-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('info_attack', models.IntegerField(blank=True, null=True)),
                ('info_defense', models.IntegerField(blank=True, null=True)),
                ('info_magic', models.IntegerField(blank=True, null=True)),
                ('info_difficulty', models.IntegerField(blank=True, null=True)),
                ('stats_hp', models.FloatField(blank=True, null=True)),
                ('stats_hp_per_level', models.FloatField(blank=True, null=True)),
                ('stats_mp', models.FloatField(blank=True, null=True)),
                ('stats_mp_per_level', models.FloatField(blank=True, null=True)),
                ('stats_movespeed', models.FloatField(blank=True, null=True)),
                ('stats_armor', models.FloatField(blank=True, null=True)),
                ('stats_armor_per_level', models.FloatField(blank=True, null=True)),
                ('stats_magic_resist', models.FloatField(blank=True, null=True)),
                ('stats_magic_resist_per_level', models.FloatField(blank=True, null=True)),
                ('stats_attack_range', models.FloatField(blank=True, null=True)),
                ('stats_hp_regen', models.FloatField(blank=True, null=True)),
                ('stats_hp_regen_per_level', models.FloatField(blank=True, null=True)),
                ('stats_mp_regen', models.FloatField(blank=True, null=True)),
                ('stats_mp_regen_per_level', models.FloatField(blank=True, null=True)),
                ('stats_crit', models.FloatField(blank=True, null=True)),
                ('stats_crit_per_level', models.FloatField(blank=True, null=True)),
                ('stats_attack_damage', models.FloatField(blank=True, null=True)),
                ('stats_attack_damage_per_level', models.FloatField(blank=True, null=True)),
                ('stats_attack_speed', models.FloatField(blank=True, null=True)),
                ('stats_attack_speed_per_level', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=None)),
                ('mana', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
