# Generated by Django 3.1.2 on 2020-10-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='id',
        ),
        migrations.AlterField(
            model_name='champion',
            name='name',
            field=models.CharField(default=None, max_length=255, primary_key=True, serialize=False),
        ),
    ]
