# Generated by Django 3.1.2 on 2020-10-23 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201022_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='image',
        ),
        migrations.CreateModel(
            name='ChampionSkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=None)),
                ('champion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.champion')),
            ],
        ),
    ]
